{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-infra-provider-truenas.fullname" . }}
  labels:
    {{- include "omni-infra-provider-truenas.labels" . | nindent 4 }}
type: Opaque
stringData:
  OMNI_SERVICE_ACCOUNT_KEY: {{ .Values.secrets.omniServiceAccountKey | quote }}
  TRUENAS_API_KEY: {{ .Values.secrets.truenasApiKey | quote }}
{{- end }}
