package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestChangelog_VersionEntriesUseBracketFormat enforces the awk-extractable
// version-header format expected by the release workflow.
//
// .github/workflows/release.yaml extracts release notes via:
//
//	awk "/^## \\[v?${VERSION}\\]/{found=1; next} /^## \\[/{if(found) exit} found{print}"
//
// which only matches headers in the form `## [vX.Y.Z]` (with brackets). If a
// future contributor writes `## v0.14.7 — Title` (no brackets), the awk
// extraction fails silently, the release workflow falls back to autogenerated
// `git log` notes, and the published release page is wrong — and immutable.
//
// This test scans CHANGELOG.md for any `## ` line that mentions a vX.Y.Z
// version number anywhere AND fails if it doesn't use the bracket form.
func TestChangelog_VersionEntriesUseBracketFormat(t *testing.T) {
	t.Parallel()

	// Test runs from cmd/omni-infra-provider-truenas/ — CHANGELOG is two levels up.
	src, err := os.ReadFile(filepath.Join("..", "..", "CHANGELOG.md"))
	require.NoError(t, err, "CHANGELOG.md must exist at repo root")

	// Match `## ` followed by anything that contains vX.Y.Z somewhere on the line.
	versionLine := regexp.MustCompile(`^##\s+.*v\d+\.\d+\.\d+`)

	// Match the canonical bracket format that the release workflow's awk extractor expects.
	bracketed := regexp.MustCompile(`^##\s+\[v?\d+\.\d+\.\d+\]`)

	var bad []string

	for i, line := range strings.Split(string(src), "\n") {
		// Skip lines inside fenced code blocks — they're not headers.
		if strings.HasPrefix(strings.TrimSpace(line), "```") {
			continue
		}

		if !versionLine.MatchString(line) {
			continue
		}

		if !bracketed.MatchString(line) {
			bad = append(bad, "line "+strconv.Itoa(i+1)+": "+line)
		}
	}

	assert.Empty(t, bad,
		"CHANGELOG.md version entries must use `## [vX.Y.Z]` format with brackets — the release workflow's awk extractor only matches the bracket form. Without brackets, release notes silently fall back to git-log autogeneration. Bad lines:\n%s",
		strings.Join(bad, "\n"))
}

// TestChangelog_EveryVersionHasReferenceLink pins the convention that every
// version header has a corresponding `[vX.Y.Z]: https://...` reference link
// at the bottom of the file. Missing reference links don't break the awk
// extraction but do produce broken `[vX.Y.Z]` links in the rendered docs.
func TestChangelog_EveryVersionHasReferenceLink(t *testing.T) {
	t.Parallel()

	src, err := os.ReadFile(filepath.Join("..", "..", "CHANGELOG.md"))
	require.NoError(t, err)

	body := string(src)

	// Find all version headers.
	headerRe := regexp.MustCompile(`(?m)^##\s+\[(v\d+\.\d+\.\d+)\]`)
	headers := headerRe.FindAllStringSubmatch(body, -1)
	require.NotEmpty(t, headers, "CHANGELOG.md must contain at least one ## [vX.Y.Z] header")

	for _, h := range headers {
		version := h[1]
		// Reference link form: `[vX.Y.Z]: https://...`
		refRe := regexp.MustCompile(`(?m)^\[` + regexp.QuoteMeta(version) + `\]:\s+https?://`)
		assert.True(t, refRe.MatchString(body),
			"CHANGELOG.md has version header [%s] but no matching reference link `[%s]: https://...` at the bottom — the bracket-format link will render as broken text", version, version)
	}
}
