// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: api/specs/specs.proto

package specs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineSpec is stored in Omni in the infra provisioner state.
type MachineSpec struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Uuid                string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Schematic           string                 `protobuf:"bytes,2,opt,name=schematic,proto3" json:"schematic,omitempty"`
	TalosVersion        string                 `protobuf:"bytes,3,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	ImageId             string                 `protobuf:"bytes,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	VmId                int32                  `protobuf:"varint,5,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ZvolPath            string                 `protobuf:"bytes,6,opt,name=zvol_path,json=zvolPath,proto3" json:"zvol_path,omitempty"`
	CdromDeviceId       int32                  `protobuf:"varint,7,opt,name=cdrom_device_id,json=cdromDeviceId,proto3" json:"cdrom_device_id,omitempty"`
	LastUpgradeSnapshot string                 `protobuf:"bytes,8,opt,name=last_upgrade_snapshot,json=lastUpgradeSnapshot,proto3" json:"last_upgrade_snapshot,omitempty"` // Snapshot ID from the most recent pre-upgrade snapshot
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_api_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_api_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MachineSpec) GetSchematic() string {
	if x != nil {
		return x.Schematic
	}
	return ""
}

func (x *MachineSpec) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *MachineSpec) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *MachineSpec) GetVmId() int32 {
	if x != nil {
		return x.VmId
	}
	return 0
}

func (x *MachineSpec) GetZvolPath() string {
	if x != nil {
		return x.ZvolPath
	}
	return ""
}

func (x *MachineSpec) GetCdromDeviceId() int32 {
	if x != nil {
		return x.CdromDeviceId
	}
	return 0
}

func (x *MachineSpec) GetLastUpgradeSnapshot() string {
	if x != nil {
		return x.LastUpgradeSnapshot
	}
	return ""
}

var File_api_specs_specs_proto protoreflect.FileDescriptor

const file_api_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x15api/specs/specs.proto\x12\ftruenasspecs\"\x8d\x02\n" +
	"\vMachineSpec\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tschematic\x18\x02 \x01(\tR\tschematic\x12#\n" +
	"\rtalos_version\x18\x03 \x01(\tR\ftalosVersion\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\tR\aimageId\x12\x13\n" +
	"\x05vm_id\x18\x05 \x01(\x05R\x04vmId\x12\x1b\n" +
	"\tzvol_path\x18\x06 \x01(\tR\bzvolPath\x12&\n" +
	"\x0fcdrom_device_id\x18\a \x01(\x05R\rcdromDeviceId\x122\n" +
	"\x15last_upgrade_snapshot\x18\b \x01(\tR\x13lastUpgradeSnapshotB=Z;github.com/bearbinary/omni-infra-provider-truenas/api/specsb\x06proto3"

var (
	file_api_specs_specs_proto_rawDescOnce sync.Once
	file_api_specs_specs_proto_rawDescData []byte
)

func file_api_specs_specs_proto_rawDescGZIP() []byte {
	file_api_specs_specs_proto_rawDescOnce.Do(func() {
		file_api_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_specs_specs_proto_rawDesc), len(file_api_specs_specs_proto_rawDesc)))
	})
	return file_api_specs_specs_proto_rawDescData
}

var file_api_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_specs_specs_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: truenasspecs.MachineSpec
}
var file_api_specs_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_specs_specs_proto_init() }
func file_api_specs_specs_proto_init() {
	if File_api_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_specs_specs_proto_rawDesc), len(file_api_specs_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_specs_specs_proto_goTypes,
		DependencyIndexes: file_api_specs_specs_proto_depIdxs,
		MessageInfos:      file_api_specs_specs_proto_msgTypes,
	}.Build()
	File_api_specs_specs_proto = out.File
	file_api_specs_specs_proto_goTypes = nil
	file_api_specs_specs_proto_depIdxs = nil
}
