apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omni-infra-provider

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/bearbinary/omni-infra-provider-truenas
    newTag: latest
